from os.path import abspath, join, dirname


class Content:
    def __init__(self):
        
        self.about_us_content: dict= {
            "EN": {
                "whoAreWe": "was founded in 2019. An entity that is responsible for providing traders with the best experience in Forex, and deliver one message: «TRADE ON THE RIGHT WAY».",
                "vision": "- Install the right trading culture in the Middle East as a type of profitable investment that the whole world needs in recent times.\n\n-Reach the best international standards in Forex World.\n\n-Learn how to make money by trading. \n\n- Present comprehensive services in the world of financial markets through various methods that help traders achieve the greatest profit intelligently.\n\n- Spread the West's approach to trading and considering it an investment that must be learned properly to reap the largest profits.",
                "mission": "- Focus on providing quality financial services\n\n- Provide reliable financial advice.\n\n- Create safe and reliable investments.\n\n- Adhere to ethical practices .\n\n- Help clients secure their financial future.\n\n- Provide excellent customer service.\n\n- Teach the public to trade the right way.\n\n- Warning against companies that use the term “trading” in order to delude the public into obtaining large profits without learning.\n\n- Availability of free educational value to teach the basics of trading.\n\n- View the latest trading strategies and share them with traders.",
                "education": "Education",
                "educationContent": "- Online Courses.\n\n- Offline Courses.\n\n- Free educaional content for beginners and advcanced audience.\n\n- Free Webinars.\n\n- Outdoor Events.",
                "informing": "Informing",
                "informingContent": "- Daily News on Our Website and platforms.\n\n- Articles on website.\n\n- Anylsing.\n\n- Weekly Economic Agenda.",
                "trading": "Trading",
                "tradingContent": "- Consulting.\n\n- Recommendatins.\n\n- Open Accounts.\n\n- Competations.",
            },
            "AR": {
                "whoAreWe": "تأسست عام 2019. كيان مسؤول لتزويد المتداولين بأفضل تجربة في الفوركس، وإيصال رسالة واحدة: التداول على الطريق  الصحيح",
                "vision": "-تثبيت  ثقافة التداول الصحيحة في الشرق الأوسط كنوع من الاستثمار المربح الذي يحتاجه العالم كله في الآونة الأخيرة.\n\n-الوصول إلى أفضل المعايير العالمية في عالم الفوركس.\n\n-تعلم كيفية كسب المال عن طريق التداول.\n\n- تقديم خدمات شاملة في عالم المال\n\n- الأسواق من خلال وسائل مختلفة تساعد المتداولين تحقيق أكبر قدر من الربح بذكاء.\n\n- نشر منهج الغرب في التجارة والنظر فيه استثمار يجب تعلمه بشكل صحيح لجني ثماره أكبر الأرباح",
                "mission": "- التركيز على تقديم خدمات مالية عالية الجودة\n\n- تقديم المشورة المالية الموثوقة.\n\n- خلق استثمارات آمنة وموثوقة.\n\n- الالتزام بالممارسات الأخلاقية.\n\n- مساعدة العملاء على تأمين مستقبلهم المالي.\n\n- تقديم خدمة عملاء ممتازة.\n\n- تعليم الجمهور التجارة بالطريقة الصحيحة.\n\n- التحذير من الشركات التي تستخدم مصطلح \"التداول\" بهدف التضليل\n\nالجمهور للحصول على أرباح كبيرة دون التعلم.\n\n- توافر قيمة تعليمية مجانية لتعليم أساسيات التداول.\n\n- عرض أحدث استراتيجيات التداول ومشاركتها مع المتداولين",
                "education": "التعليم",
                "educationContent": "-  دروس مباشرة على الإنترنت.\n\n- دورات أوفلاين.\n\n- محتوى تعليمي مجاني لـ المبتدئين والمتقدمين\n\n- ندوات عبر الإنترنت مجانية.\n\n- الفعاليات الخارجية",
                "informing": "أخبار",
                "informingContent": "- الأخبار اليومية على موقعنا \والمنصات.\n\n- مقالات على الموقع.\n\n- تحليلات.\n\n- الأجندة الاقتصادية الأسبوعية.",
                "trading": "تداول",
                "tradingContent": "-الاستشارة-\n\nالتوصيات.\n\n- حسابات مفتوحة.\n\n- المسابقات.",

            }
        }
        self.global_: dict = {
            "EN": {
                "platformTitle": "FOREXology",
                "footerMsg": "was founded in 2019. An entity that is responsible for providing traders with the best experience in Forex, and deliver one message: «TRADE ON THE RIGHT WAY».",
                "lightToFindUs": "Trade on the right way!",
                "copyrightMsg": "All Copyrights reserved @ FOREXology, 2023",
                "search": "Search",
                "trendingNow": "Trending Now",
                "dontHaveAccount": "Don't have an account? Join us now!",
                "alreadyHaveAccount": "Have an account? Login now!",
                "name": "Name",
                "phoneNumber": "Phone Number",
                "email": "Email",
                "password": "Password",
                "homeEntryMsg": "Best of the week",
                "mostRecent": "Most Recent",
                "allArticles": "All Articles",
                "random": "Random",
                "all": "All",
                "ourLatestArticles": "Our Latest Articles",
                "ourArticles": "Our Articles",
                "featured": "Featured",
                "trending": "Trending",
                "ourBestWriters": "Our best <br><span>Writers</span>",
                "incaseYouMissed": "In Case You Missed!",
                "incaseYouMissedMsg": "In case you missed these articles, Check them out now!",
                "randomArticles": "Random Articles!",
                "randomArticlesMsg": "Based on your pervious choises, We've picked these articles for you!",
                "wannaJoinUs": "Curious about<br><span> Joining Us</span>",
                "applications": "Applications",
                "le": "L.E.",
                "classification": "Classification",
                "classifications": "Classifications",
                "category": "Category",
                "categories": "Categories",
                "writer": "Writer",
                "writers": "Writers",
                "articles": "Articles",
                "writtenBy": "Written By",
                "unavailable": "Unavailable",
                "listenMsg": "Listen to the article!",
                "unavailableMsg": "The article audio not available!",
                "shareMsg": "Share this article!",
                "rateMsg": "Rate this article!",
                "commentMsg": "Leave a comment!",
                "whatsYouWantToRead": "You want to read what?",
                "whatsYouWantToReadMsg": "Choose what do you want to read!",
                "filter": "Filter",
                "filterMsg": "Get the exact articles you're searching for!",
                "articleTitle": "Article Title",
                "discoverCategories": "Discover our <span class=\"underline\">Categories</span>",
                "discoverCategoriesMsg": "We've classified our articles to make it easy for you to find what you are searching for!",
                "featuredCategories": "Featured Categories",
                "featuredCategoriesMsg": "We've chosen these categories for you!",
                "allCategories": "All Categories",
                "allCategoriesMsg": "Check out all categories we have!",
                "latestArticles": "Latest Articles",
                "latestArticlesMsg": "Discover the latest articles now!",
                "careers": "Careers",
                "resetYourPassword": "Reset your password",
                "profilePicture": "Profile Picture",
                "coverPicture": "Cover Picture",
                "allCareers": "All Careers",
                "weSearchingForYou": "We're searching for you like you do!",
                "riskwarning": "Risk Warning",
                "riskwarningMsg": "Trading using leverage in the financial markets involves very high risks that are not suitable for all types of investors. You must understand the amount of risk that your money may be exposed to. All opinions, analyses, recommendations and content presented on the site are for general information and should not be taken as a tool for making any investment decisions, whether to buy or sell.",
                "agenda": "Economic Agenda",
                "agendaMsg": "Follow up the news and times that affect marketplaces!",
                "welcomeBack": "Welcome Back",
                "aboutMsg": "Curious about know more about us?",
                "coursesMsg": "Start your journey to \"Trade on the Right way\"!",
                "price": "Price", 
                "sessions": "Sessions",
                "courseContent": "Course Content",
                "students": "Students"
            },
            "AR": {
                "platformTitle": "فوركسولوچي",
                "footerMsg": "تأسست عام 2019. كيان مسؤول لتزويد المتداولين بأفضل تجربة في الفوركس، وإيصال رسالة واحدة: التداول على الطريق  الصحيح",
                "lightToFindUs": "تداول على الطريقة الصحيحة!",
                "copyrightMsg": "All Copyrights reserved @ FOREXology, 2023",
                "search": "بحث",
                "trendingNow": "شائع الآن",
                "dontHaveAccount": "ليس لديك حساب؟ انضم إلينا الآن!",
                "alreadyHaveAccount": "هل لديك حساب؟ سجل الدخول الآن!",
                "name": "الاسم",
                "phoneNumber": "رقم الهاتف",
                "email": "البريد إلكتروني",
                "password": "كلمة المرور",
                "homeEntryMsg": "أفضل ما في الأسبوع",
                "mostRecent": "الأحدث",
                "allArticles": "جميع المقالات",
                "random": "عشوائي",
                "all": "الكل",
                "ourLatestArticles": "أحدث المقالات",
                "ourArticles": "المقالات",
                "featured": "المُختار",
                "trending": "الشائع",
                "ourBestWriters": "أفضل <br><span>الكُتّاب</span> لدينا",
                "incaseYouMissed": "مقالات ذات صلة",
                "incaseYouMissedMsg": "في حال فاتتك هذه المقالات ، تحقق منها الآن!",
                "randomArticles": "مقالات آخرى!",
                "randomArticlesMsg": "بناءً على اختياراتك السابقة ، اخترنا لك هذه المقالات!!",
                "wannaJoinUs": "مهتم بأن<br><span>تنضم إلينا</span>",
                "applications": "المتقدمين للوظيفة",
                "le": "L.E.",
                "classification": "التصنيف",
                "classifications": "التصنيفات",
                "category": "الفئة",
                "categories": "الفئات",
                "writer": "الكاتب",
                "writers": "الكُتًاب",
                "articles": "المقالات",
                "writtenBy": "كٌتبت بواسطة",
                "unavailable": "غير متوفر",
                "listenMsg": "إستمع إلى المقال!",
                "unavailableMsg": "النسخة الصوتية من المقال غير متوفرة!",
                "shareMsg": "أنشر هذا المقال!",
                "rateMsg": "قيم هذا المقال!",
                "commentMsg": "اترك تعليقاً!",
                "whatsYouWantToRead": "ماذا تريد أن تقرأ؟",
                "whatsYouWantToReadMsg": "اختر ما تريد قراءته!",
                "filter": "بحث",
                "filterMsg": "احصل على المقالات التي تبحث عنها!",
                "articleTitle": "عنوان المقال",
                "discoverCategories": "تفقد <span class=\"underline\">الفئات</span> التي نتناولها",
                "discoverCategoriesMsg": "لقد قمنا بتصنيف مقالاتنا لتسهيل العثور على ما تبحث عنه!",
                "featuredCategories": "الفئات المختارة",
                "featuredCategoriesMsg": "الفئات التي قمنا بإختيارها لك!",
                "allCategories": "الفئات",
                "allCategoriesMsg": "تفقد جميع الفئات التي نتناولها",
                "latestArticles": "أحدث المقالات",
                "latestArticlesMsg": "تفقد أخر المقالات المنشورة!",
                "careers": "الوظائف",
                "resetYourPassword": "إسترجع كلمة مرور حسابك",
                "profilePicture": "الصورة الشخصية",
                "coverPicture": "صورة الغلاف",
                "allCareers": "جميع الوظائف",
                "weSearchingForYou": "نحن نبحث عنك كما تفعل!",
                "riskwarning": "تحذير المخاطرة",
                "riskwarningMsg": "المتاجرة باستخدام الروافع المالية في أسواق المال ينطوي عليها مخاطر عالية جدًا لا تتناسب مع جميع أنواع المستثمرين، يجب عليك أن تستوعب حجم المخاطرة التي قد تتعرض لها أموالك. جميع ما يطرح في الموقع من آراء وتحليلات وتوصيات ومحتويات هو من باب المعلومات العامة ولا يجب أن يتخذ كأداة لاتخاذ أي قرارات استثمارية بالبيع أو الشراء. ",
                "agenda": "الأجندة الإقتصادية",
                "agendaMsg": "تابع الأخبار والمواقيت التي ترثؤ على الأسواق المالية!!",
                "welcomeBack": "أهلاً بعودتك",
                "aboutMsg": "مهتم أن تعرف المزيد عن من نكون؟",
                "coursesMsg": "أبدأ رحلتك في التداول بالطريقة الصحيحة",
                "price": "السعر", 
                "sessions": "المحاضرات",
                "courseContent": "محتوى الدورة",
                "students": "عدد الطلاب"
            }
        }

        self.tabs: dict = {
            "EN": {
                "home": "Home",
                "courses": "Courses",
                "articles": "Articles",
                "tools": "Tools",
                "categories": "Categories",
                "careers": "Careers",
                "audioArticles": "Audio Articles",
                "aboutUs": "About Us",
                "classification": "Classification",
                "passwordReset": "Password Reset",
                "profile": "Profile",
                "agenda": "Economic Agenda"
            },
            "AR": {
                "home": "الرئيسية",
                "courses": "الدورات",
                "articles": "المقالات",
                "tools": "الأدوات",
                "categories": "الفئات",
                "careers": "الوظائف",
                "audioArticles": "المقالات الصوتية",
                "aboutUs": "نبذة عنا",
                "classification": "التصنيفات",
                "passwordReset": "إستعادة كلمة المرور",
                "profile": "الصفحة الشخصية",
                "agenda": "الأجندة الإقتصادية"
            }
        }

        self.actions: dict = {
            "EN": {
                "login": "Login",
                "signup": "Sign Up",
                "seeMore": "See more",
                "rememberMe": "Remember me",
                "forgetPassword": "Forget Password?",
                "seeAllArticles": "See all articles",
                "seeMyArticles": "See My Articles",
                "seeAllJobs": "See All Jobs",
                "apply": "Apply",
                "applyNow": "Apply Now",
                "listen": "Listen",
                "share": "Share",
                "rate": "Rate",
                "comment": "Comment",
                "shareLinkVia": "Share article via...",
                "shareLink": "Share article's link!",
                "clear": "Clear",
                "findEmail": "Find Email",
                "sendCodeAgain": "Send code again",
                "changeEmail": "Change Email",
                "validateYourEmail": "Validate your email",
                "Validate": "Validate",
                "completeProfile": "Complete Profile",
                "submit": "Submit",
                "cancel": "Cancel",
                "checkThisOut": "Check this out!",
                "goBack": "Go Back",
                "continueCourse": "Continue Course",
                "enrollNow": "Enroll Now",
                "addToWishlist": "Add to wishlist",
            },
            "AR": {
                "login": "تسجيل الدخول",
                "signup": "تسجيل الإشتراك",
                "seeMore": "شاهد المزيد",
                "rememberMe": "تذكرنى",
                "forgetPassword": "نسيت كلمة المرور?",
                "seeAllArticles": "تصفح جميع المقالات",
                "seeMyArticles": "تصفح مقالاتي",
                "seeAllJobs": "تصفح جميع الوظائف",
                "apply": "قدم",
                "applyNow": "قدم الآن",
                "listen": "استمع",
                "share": "شارك",
                "rate": "قيم",
                "comment": "أترك تعليقاً",
                "shareLinkVia": "شارك المقال عن طريق...",
                "shareLink": "شارك رابط المقال",
                "clear": "مسح",
                "findEmail": "البحث عن البريد الإلكتروني",
                "sendCodeAgain": "ارسل الرمز مجددا",
                "changeEmail": "تغيير الايميل",
                "validateYourEmail": "تحقق من صحة بريدك الإلكتروني",
                "Validate": "تحقق",
                "completeProfile": "أكمل الملف الشخصي",
                "submit": "تأكيد",
                "cancel": "إلغاء",
                "checkThisOut": "تحقق من هذا!",
                "goBack": "عُد",
                "continueCourse": "أكمل الدورة",
                "enrollNow": "التحق الآن",
                "addToWishlist": "أضف إلى قائمة الاهتمامات",


            }
        }

        self.placeholders: dict = {
            "EN": {
                "search": "Search by name, keywords, etc...",
                "emailUsernameFieldPlaceholder": "Email Address or Username",
                "emailFieldPlaceholder": "Email Address",
                "nameFieldPlaceholder": "Name",
                "passwordFieldPlaceholder": "Enter your Password!",
                "repasswordFieldPlaceholder": "Re-enter your Password!",
            }, "AR": {
                "search": "Search by name, keywords, etc...",
                "emailUsernameFieldPlaceholder": "Email Address or Username",
                "emailFieldPlaceholder": "Email Address",
                "nameFieldPlaceholder": "Name",
                "passwordFieldPlaceholder": "Enter your Password!",
                "repasswordFieldPlaceholder": "Re-enter your Password!",
            }
        }

        self.salary_types: dict = {
            "EN": {
                0: "Per Month",
                1: "Per Task",
                2: "Per Milestone",
                3: "Per Project",
                4: "Long-time Contract",
                5: "Short-time Contract",
            },
            "AR": {
                0: "شهرياً",
                1: "مقابل المهمة",
                2: "مقابل المرحلة",
                3: "مقابل المشروع",
                4: "عقد طويل الأمد",
                5: "عقد قصير الأمد",
            },
        }

        self.job_types: dict = {
            "EN": {
                0: "Full Time",
                1: "Part Time",
                2: "Freelancer",
                3: "Hour Based Rate",
            },
            "AR": {
                0: "دوام كلي",
                1: "دوام جزئي",
                2: "مستقل",
                3: "حسب الوقت اللازم",
            },
        }
        
        self.errors: dict= {
            "EN": {
                "notFound": "Not Found",
                "notFoundMsg": "We didn't found the page or data you're searching for!",
                "internalServerError": "Internal Server Error",
                "internalServerErrorMsg": "There is an error. Try again later!",
            },
            "AR": {
                "notFound": "غير موجود",
                "notFoundMsg": "لم نعثر على الصفحة أو البيانات التي تبحث عنها!",
                "internalServerError": "خطأ في الخادم الداخلي",
                "internalServerErrorMsg": "هنالك خطأ. حاول مرة أخرى في وقت لاحق!",
            }
        }

        self.agenda: dict= {
            "EN": {
                "event": "Event",
                "current": "Current",
                "pervious": "Pervious",
                "predicted": "Predicted",
                "importance": "Importance",
                "time": "Time",
            },
            "AR": {
                "currency": "العملة",
                "event": "الحدث",
                "current": "الحالي",
                "pervious": "السابق",
                "predicted": "المتوقع",
                "importance": "الأهمية",
                "time": "الوقت",
            }
        }

        self.courses= {
            "EN": {
                "completeSessions": "Completed Sessions",
                "courseCompletion": "Courses Completing",
                "testsPassed": "Tests Passed",
            },
            "AR": {
                "completeSessions": "المحاضرات المكتملة",
                "courseCompletion": "إكمال الدورة",
                "testsPassed": "الاختبارات التي تم تجاوزها",
            },
        }
